/**
 * German cities offered in the Discover location dropdown. Country is fixed to
 * Germany, so this is the full place list. Covers every city above ~90k
 * population plus notable tech/job hubs — the value is passed verbatim as the
 * `location` filter to both the Supabase search and the Adzuna/Jooble `where`
 * parameters, so spellings use the common German form the APIs expect.
 */
export const GERMAN_CITIES = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt am Main",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Essen",
  "Bremen",
  "Dresden",
  "Hannover",
  "Nürnberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Mannheim",
  "Karlsruhe",
  "Augsburg",
  "Wiesbaden",
  "Mönchengladbach",
  "Gelsenkirchen",
  "Aachen",
  "Braunschweig",
  "Chemnitz",
  "Kiel",
  "Halle (Saale)",
  "Magdeburg",
  "Freiburg im Breisgau",
  "Krefeld",
  "Mainz",
  "Lübeck",
  "Erfurt",
  "Oberhausen",
  "Rostock",
  "Kassel",
  "Hagen",
  "Potsdam",
  "Saarbrücken",
  "Hamm",
  "Ludwigshafen am Rhein",
  "Mülheim an der Ruhr",
  "Oldenburg",
  "Osnabrück",
  "Leverkusen",
  "Heidelberg",
  "Darmstadt",
  "Solingen",
  "Herne",
  "Regensburg",
  "Neuss",
  "Paderborn",
  "Ingolstadt",
  "Offenbach am Main",
  "Fürth",
  "Ulm",
  "Heilbronn",
  "Pforzheim",
  "Würzburg",
  "Wolfsburg",
  "Göttingen",
  "Bottrop",
  "Reutlingen",
  "Koblenz",
  "Bremerhaven",
  "Bergisch Gladbach",
  "Erlangen",
  "Jena",
  "Trier",
  "Salzgitter",
  "Siegen",
  "Hildesheim",
  "Cottbus",
  "Kaiserslautern",
  "Gütersloh",
  "Tübingen",
  "Flensburg",
  "Konstanz"
] as const;
